'use client';

import { Button } from '@/components/ui/button';
import { Card,CardContent,CardHeader,CardTitle } from '@/components/ui/card';
import ErrorBoundary from '@/components/ui/error-boundary';
import { ToggleGroup } from '@/components/ui/toggle-group';
import { CLIENT_ENV } from '@/lib/env-config';
import { useFrameContext } from '@/lib/frame-context';
import { PIXOTCHI_ADDRESS,SEED_ADDRESS } from '@/lib/swap/constants';
import { useTabVisibility } from "@/lib/tab-visibility-context";
import { sdk } from '@farcaster/miniapp-sdk';
import { Copy } from 'lucide-react';
import Image from 'next/image';
import { useEffect,useState,type ReactNode } from 'react';
import { toast } from 'react-hot-toast';
import { erc20Abi } from 'viem';
import { useAccount,useReadContract } from 'wagmi';
import TradingViewWidget from './TradingViewWidget';
import PixotchiSwapPanel from './pixotchi-swap-panel';

const INITIAL_SEED_SUPPLY = BigInt(20_000_000) * BigInt(10) ** BigInt(18);
const PERCENTAGE_BASIS_POINTS = BigInt(10_000);
const BATCH_CLAIM_BURN_AMOUNT = Number(process.env.NEXT_PUBLIC_BATCH_CLAIM_BURN_AMOUNT || 500);
const BATCH_CLAIM_MAX_SIZE = Number(process.env.NEXT_PUBLIC_BATCH_CLAIM_MAX_SIZE || 150);
type SwapView = 'swap' | 'chart' | 'info';
type InfoToken = 'seed' | 'leaf' | 'pixotchi';

type TokenInfoSection = {
  iconSrc: string;
  iconAlt: string;
  title: ReactNode;
  body: ReactNode;
  bullets?: ReactNode[];
};

const TOKEN_INFO_OPTIONS = [
  {
    id: 'seed',
    symbol: 'SEED',
    name: 'Core economy token',
    iconSrc: '/PixotchiKit/COIN.svg',
    iconAlt: 'SEED token',
    tokenAddress: SEED_ADDRESS,
    summary: 'The fixed-supply currency that powers plant actions, upgrades, swaps, staking access, and the wider Pixotchi economy.',
  },
  {
    id: 'leaf',
    symbol: 'LEAF',
    name: 'Land progression resource',
    iconSrc: '/icons/leaf.png',
    iconAlt: 'LEAF token',
    tokenAddress: CLIENT_ENV.LEAF_CONTRACT_ADDRESS,
    summary: 'An internal progression token earned from staking SEED and used mainly to develop Lands and long-term village systems.',
  },
  {
    id: 'pixotchi',
    symbol: 'PIXOTCHI',
    name: 'Creator Coin layer',
    iconSrc: '/icons/cc.png',
    iconAlt: 'PIXOTCHI Creator Coin',
    tokenAddress: PIXOTCHI_ADDRESS,
    summary: 'A Zora Creator Coin connected to real gameplay utility, not passive ownership.',
  },
] as const satisfies ReadonlyArray<{
  id: InfoToken;
  symbol: string;
  name: string;
  iconSrc: string;
  iconAlt: string;
  tokenAddress: string;
  summary: string;
}>;

function SwapLockedState({ message }: { message: string }) {
  return (
    <div className="flex min-h-[420px] items-center justify-center rounded-xl border border-amber-500/30 bg-amber-500/10 p-6 text-center">
      <div className="mx-auto max-w-md space-y-4">
        <div className="mx-auto flex h-14 w-14 items-center justify-center rounded-full border border-amber-500/30 bg-background/70 text-2xl">
          !
        </div>
        <p className="text-lg font-semibold text-foreground">Swaps temporarily unavailable</p>
        <p className="whitespace-pre-line text-sm leading-relaxed text-muted-foreground">
          {message}
        </p>
      </div>
    </div>
  );
}

function getTokenInfoSections(
  activeToken: InfoToken,
  currentBurnedSupplyLabel: string,
  rewardsData: { volume24h: number; rewards: number } | null
): TokenInfoSection[] {
  if (activeToken === 'leaf') {
    return [
      {
        iconSrc: '/icons/stake-house.svg',
        iconAlt: 'Staking',
        title: 'Earned Through Staking',
        body: 'LEAF is generated by staking SEED. Rewards accrue over time and can be claimed, giving stakers a long-term progression resource without turning LEAF into a public-market token.',
        bullets: [
          'Stake SEED to generate LEAF continuously.',
          'Seasonal reward programs and airdrops may also distribute LEAF when active.',
          'LEAF claiming and staking management live inside the Pixotchi app and staking interfaces.',
        ],
      },
      {
        iconSrc: '/icons/village-start.png',
        iconAlt: 'Lands',
        title: 'Built For Lands',
        body: 'LEAF is mainly used for Land development: upgrading buildings, unlocking higher production tiers, and supporting long-term village efficiency.',
      },
      {
        iconSrc: '/icons/marketplace.svg',
        iconAlt: 'Marketplace',
        title: 'In-Game Marketplace Only',
        body: 'LEAF has no external liquidity pool. It is tradable only inside the Marketplace building through player-created SEED/LEAF orders, keeping price discovery inside the game economy.',
      },
    ];
  }

  if (activeToken === 'pixotchi') {
    return [
      {
        iconSrc: '/icons/zora.png',
        iconAlt: 'Zora',
        title: 'Creator Coin, Game-First',
        body: 'A Zora Creator Coin adapted for gameplay, adding useful actions beyond open-market trading.',
      },
      {
        iconSrc: '/icons/Avatar2.svg',
        iconAlt: 'Wallet profile',
        title: 'In-Game Utility Layer',
        body: `Covers instant building upgrades, Casino plays, and batch claims of up to ${BATCH_CLAIM_MAX_SIZE} buildings for ${BATCH_CLAIM_BURN_AMOUNT} tokens.`,
      },
      {
        iconSrc: '/icons/cc.png',
        iconAlt: 'PIXOTCHI token',
        title: 'Tokenomics',
        body: 'Fixed 1B supply: 50% entered the market and 50% vests to the creator over five years. Zora fees deepen permanent liquidity.',
      },
    ];
  }

  return [
    {
      iconSrc: '/icons/fire.svg',
      iconAlt: 'Burn',
      title: (
        <span className="flex flex-wrap items-baseline gap-x-2 gap-y-1">
          <span>70% In-Game Burn</span>
          <span className="text-xs font-medium text-muted-foreground">
            (Current burnt supply: {currentBurnedSupplyLabel})
          </span>
        </span>
      ),
      body: 'Currently, 70% of SEED spent inside the game on items or upgrades is permanently burned. The remaining 30% is recycled into the rewards pool.',
    },
    {
      iconSrc: '/icons/tax.svg',
      iconAlt: 'Tax',
      title: '5% Buy/Sell Tax',
      body: 'A 5% tax applies to SEED swaps to sustain the ecosystem and support rewards, development, and liquidity.',
      bullets: [
        <><span className="font-semibold text-foreground">2% to Player Rewards:</span> Distributed as ETH based on plant ranking.</>,
        <><span className="font-semibold text-foreground">2% to Project Treasury:</span> Funds ongoing development and operations.</>,
        <><span className="font-semibold text-foreground">1% to Liquidity Pool:</span> Added to the SEED/ETH pool for stability.</>,
      ],
    },
    {
      iconSrc: '/icons/ethlogo.svg',
      iconAlt: 'Rewards',
      title: rewardsData
        ? `$${rewardsData.rewards.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })} Rewards Distributed Today`
        : 'Rewards Distributed Today',
      body: (
        <>
          2% of SEED trading volume is distributed daily to plants as ETH based on their points. Higher points = larger rewards.
          {rewardsData && ` Based on $${rewardsData.volume24h.toLocaleString(undefined, { maximumFractionDigits: 0 })} volume in the last 24h.`}
        </>
      ),
    },
  ];
}

function TokenInfoPanel({
  activeToken,
  currentBurnedSupplyLabel,
  isMiniApp,
  rewardsData,
  setActiveToken,
}: {
  activeToken: InfoToken;
  currentBurnedSupplyLabel: string;
  isMiniApp: boolean;
  rewardsData: { volume24h: number; rewards: number } | null;
  setActiveToken: (token: InfoToken) => void;
}) {
  const activeTokenInfo =
    TOKEN_INFO_OPTIONS.find((token) => token.id === activeToken) ?? TOKEN_INFO_OPTIONS[0];
  const sections = getTokenInfoSections(activeToken, currentBurnedSupplyLabel, rewardsData);

  const seedNote =
    'SEED was launched independently via BaseSwap with 100% of the supply (20M) in circulation, with no pre-mint or team allocation. Acquiring SEED does not represent an investment contract or financial advice.';

  const copyContractAddress = async () => {
    try {
      await navigator.clipboard.writeText(activeTokenInfo.tokenAddress);
      toast.success(`${activeTokenInfo.symbol} contract copied`);
    } catch {
      toast.error('Could not copy the contract address');
    }
  };

  return (
    <div className="space-y-4 text-sm lg:grid lg:grid-cols-[minmax(11rem,14rem)_minmax(0,1fr)] lg:items-start lg:gap-5 lg:space-y-0">
      <div className="space-y-3">
        <div
          className="grid grid-cols-3 gap-2 lg:grid-cols-1"
          role="radiogroup"
          aria-label="Token information"
        >
          {TOKEN_INFO_OPTIONS.map((token) => {
            const isSelected = activeToken === token.id;
            return (
              <button
                key={token.id}
                type="button"
                role="radio"
                aria-checked={isSelected}
                aria-label={token.symbol}
                title={token.symbol}
                onClick={() => setActiveToken(token.id)}
                className={`flex min-w-0 items-center justify-center gap-1 rounded-[var(--radius-nav)] border px-1.5 py-2 text-[10px] font-semibold transition-[background-color,border-color,color,box-shadow] duration-[var(--motion-quick)] ease-[var(--ease-standard)] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 ring-offset-background min-[390px]:gap-1.5 min-[390px]:px-2 min-[390px]:text-xs lg:justify-start lg:px-3 ${
                  isSelected
                    ? 'border-primary/30 bg-primary bg-[image:var(--gradient-control-active)] text-primary-foreground shadow-[var(--shadow-control)]'
                    : 'border-border/60 bg-background/45 text-foreground/80 shadow-[var(--shadow-hairline)] hover:border-primary/30 hover:bg-[hsl(var(--nav-hover-bg))] hover:text-primary'
                }`}
              >
                <Image
                  src={token.iconSrc}
                  alt=""
                  width={20}
                  height={20}
                  className="h-5 w-5 shrink-0 rounded-full"
                  aria-hidden="true"
                />
                <span className="min-w-0 leading-none">{token.symbol}</span>
              </button>
            );
          })}
        </div>

        <div className="rounded-[var(--radius-panel)] border border-border/60 bg-background/35 p-3 shadow-[var(--shadow-hairline)]">
          <div className="flex items-start gap-3">
            <Image
              src={activeTokenInfo.iconSrc}
              alt={activeTokenInfo.iconAlt}
              width={44}
              height={44}
              className="h-11 w-11 shrink-0 rounded-full object-contain"
            />
            <div className="min-w-0">
              <p className="text-sm font-semibold leading-tight text-foreground">
                {activeTokenInfo.symbol}
              </p>
              <p className="mt-0.5 text-xs font-medium text-muted-foreground">
                {activeTokenInfo.name}
              </p>
              <p className="mt-2 text-xs leading-relaxed text-muted-foreground">
                {activeTokenInfo.summary}
              </p>
            </div>
          </div>
          <button
            type="button"
            onClick={copyContractAddress}
            className="mt-3 flex w-full items-center justify-between gap-2 border-t border-border/35 pt-2 text-left text-xs text-muted-foreground transition-colors hover:text-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 ring-offset-background"
            aria-label={`Copy ${activeTokenInfo.symbol} contract address`}
            title={`Copy ${activeTokenInfo.symbol} contract address`}
          >
            <span className="min-w-0 truncate font-mono">
              {activeTokenInfo.tokenAddress}
            </span>
            <Copy className="h-3.5 w-3.5 shrink-0" aria-hidden="true" />
          </button>
        </div>

        {isMiniApp && (
          <Button
            className="w-full"
            onClick={async () => {
              try {
                await sdk.actions.viewToken({ token: `eip155:8453/erc20:${activeTokenInfo.tokenAddress}` });
              } catch {
                toast.error('View Token is only available in supported Farcaster clients.');
              }
            }}
            aria-label={`View ${activeTokenInfo.symbol} token on Base`}
          >
            View {activeTokenInfo.symbol}
          </Button>
        )}
      </div>

      <div className="space-y-4">
        <div className="space-y-3">
          {sections.map((section, index) => (
            <div
              key={`${activeToken}-${index}`}
              className="flex items-start gap-3 border-t border-border/35 pt-3 first:border-t-0 first:pt-0"
            >
              <Image
                src={section.iconSrc}
                alt={section.iconAlt}
                width={20}
                height={20}
                className="mt-0.5 h-5 w-5 shrink-0 rounded-sm"
              />
              <div className="min-w-0">
                <h4 className="font-semibold leading-snug">{section.title}</h4>
                <p className="mt-1 text-xs leading-relaxed text-muted-foreground">
                  {section.body}
                </p>
                {section.bullets && (
                  <ul className="mt-2 space-y-1 pl-4 text-xs leading-relaxed text-muted-foreground [list-style:disc]">
                    {section.bullets.map((bullet, bulletIndex) => (
                      <li key={bulletIndex}>{bullet}</li>
                    ))}
                  </ul>
                )}
              </div>
            </div>
          ))}
        </div>

        {activeToken === 'seed' && (
          <div className="border-t border-border/30 pt-4">
            <p className="text-xs leading-relaxed text-muted-foreground">
              <span className="mb-2 block font-semibold text-foreground">Note:</span>
              {seedNote}
            </p>
          </div>
        )}
      </div>
    </div>
  );
}

export default function SwapTab() {
  const { address } = useAccount();
  const fc = useFrameContext();
  const isMiniApp = Boolean(fc?.isInMiniApp);
  const isSwapModuleDisabled = CLIENT_ENV.SWAP_MODULE_DISABLED;
  const swapDisabledMessage = CLIENT_ENV.SWAP_MODULE_DISABLED_MESSAGE;
  const [swapView, setSwapView] = useState<SwapView>('swap');
  const [activeInfoToken, setActiveInfoToken] = useState<InfoToken>('seed');
  const { isTabVisible } = useTabVisibility();
  const isVisible = isTabVisible('swap');
  const isChartView = swapView === 'chart';
  const isInfoView = swapView === 'info';
  const { data: seedTotalSupply } = useReadContract({
    address: SEED_ADDRESS,
    abi: erc20Abi,
    functionName: 'totalSupply',
    query: {
      enabled: isVisible,
      staleTime: 60_000,
      refetchInterval: isVisible ? 60_000 : false,
    },
  });

  // Rewards distributed today (2% of 24h volume)
  const [rewardsData, setRewardsData] = useState<{ volume24h: number; rewards: number } | null>(null);
  const currentBurnedSupplyLabel =
    typeof seedTotalSupply === 'bigint' && seedTotalSupply <= INITIAL_SEED_SUPPLY
      ? `${(Number(((INITIAL_SEED_SUPPLY - seedTotalSupply) * PERCENTAGE_BASIS_POINTS) / INITIAL_SEED_SUPPLY) / 100).toFixed(2)}%`
      : '...';

  // Refresh global balances when swap tab is visible (in case user swapped elsewhere/added funds)
  useEffect(() => {
    if (isVisible) {
      window.dispatchEvent(new Event('balances:refresh'));
    }
  }, [isVisible]);

  // Fetch rewards data (24h volume from DexScreener)
  useEffect(() => {
    const fetchRewardsData = async () => {
      try {
        const res = await fetch('/api/seed-volume');
        if (res.ok) {
          const data = await res.json();
          setRewardsData({ volume24h: data.volume24h, rewards: data.rewards });
        }
      } catch (error) {
        console.error('Failed to fetch rewards data:', error);
      }
    };
    fetchRewardsData();
  }, []);

  if (!address && !isSwapModuleDisabled) {
    return (
      <div className="text-center text-muted-foreground py-8">Connect your wallet to swap.</div>
    );
  }

  return (
    <div className="space-y-4 lg:grid lg:grid-cols-[minmax(320px,420px)_minmax(0,1fr)] lg:items-stretch lg:gap-5 lg:space-y-0 xl:grid-cols-[minmax(360px,480px)_minmax(520px,1fr)]">
      <Card
        className={`${isChartView ? 'flex flex-col aspect-square' : ''} lg:hidden`}
        padding={isChartView ? 'none' : 'md'}
      >
        <CardHeader className={isChartView ? 'pb-3 px-4 pt-4 flex-shrink-0' : ''}>
          <div className="flex items-center justify-between gap-4">
            <CardTitle>{isChartView ? 'Chart' : isInfoView ? 'Info' : 'Swap'}</CardTitle>
            <ToggleGroup
              value={swapView}
              onValueChange={(v) => setSwapView(v as SwapView)}
              options={[
                { value: 'swap', label: 'Swap' },
                { value: 'chart', label: 'Chart' },
                { value: 'info', label: 'Info' },
              ]}
              getButtonClassName={(value) =>
                isSwapModuleDisabled && value === 'swap' ? 'opacity-60' : ''
              }
            />
          </div>
        </CardHeader>
        <CardContent className={isChartView ? 'flex-1 p-4 overflow-hidden' : 'space-y-4'}>
          {swapView === 'swap' ? (
            isSwapModuleDisabled ? (
              <SwapLockedState message={swapDisabledMessage} />
            ) : (
              <ErrorBoundary variant="inline" showErrorDetails>
                <PixotchiSwapPanel />
              </ErrorBoundary>
            )
          ) : swapView === 'chart' ? (
            <TradingViewWidget />
          ) : (
            <TokenInfoPanel
              activeToken={activeInfoToken}
              currentBurnedSupplyLabel={currentBurnedSupplyLabel}
              isMiniApp={isMiniApp}
              rewardsData={rewardsData}
              setActiveToken={setActiveInfoToken}
            />
          )}
        </CardContent>
      </Card>

      <Card className="hidden lg:block lg:h-full">
        <CardHeader>
          <CardTitle>Swap</CardTitle>
        </CardHeader>
        <CardContent className="space-y-4">
          {isSwapModuleDisabled ? (
            <SwapLockedState message={swapDisabledMessage} />
          ) : (
            <ErrorBoundary variant="inline" showErrorDetails>
              <PixotchiSwapPanel />
            </ErrorBoundary>
          )}
        </CardContent>
      </Card>

      <Card className="hidden lg:flex lg:h-full lg:min-h-[360px] lg:flex-col" padding="none">
        <CardHeader className="px-4 pt-4 pb-3">
          <CardTitle>Chart</CardTitle>
        </CardHeader>
        <CardContent className="flex-1 overflow-hidden p-4">
          <TradingViewWidget />
        </CardContent>
      </Card>

      {/* Token Info Section */}
      <Card className="hidden lg:block lg:col-span-2 lg:h-fit">
        <CardHeader>
          <CardTitle>Token Info</CardTitle>
        </CardHeader>
        <CardContent>
          <TokenInfoPanel
            activeToken={activeInfoToken}
            currentBurnedSupplyLabel={currentBurnedSupplyLabel}
            isMiniApp={isMiniApp}
            rewardsData={rewardsData}
            setActiveToken={setActiveInfoToken}
          />
        </CardContent>
      </Card>
    </div>
  );
}
