import type { BarracksConfig, BarracksConfigV2, BarracksLandState, BarracksLandStateV2, BarracksRaidReport, BarracksRaidReportV2, BarracksRaidPreview, BarracksRaidPreviewV2 } from './types';
import { readTupleField, readBoolean, readAddress, readUint, readSafeUint } from './contract-value';

// Missing or malformed fields throw. Contract readers expose a recoverable error, never a fabricated empty army.
export const normalizeBarracksConfig = (value: unknown): BarracksConfig => ({
  initialized: readBoolean(readTupleField(value, 'initialized', 0)),
  enabled: readBoolean(readTupleField(value, 'enabled', 1)),
  buildToken: readAddress(readTupleField(value, 'buildToken', 2)),
  buildCost: readUint(readTupleField(value, 'buildCost', 3)),
  buildReceiver: readAddress(readTupleField(value, 'buildReceiver', 4)),
  trainingToken: readAddress(readTupleField(value, 'trainingToken', 5)),
  trainingCost: readUint(readTupleField(value, 'trainingCost', 6)),
  trainingReceiver: readAddress(readTupleField(value, 'trainingReceiver', 7)),
  trainingTimePerTroop: readUint(readTupleField(value, 'trainingTimePerTroop', 8)),
  attackCooldown: readUint(readTupleField(value, 'attackCooldown', 9)),
  defenseCooldown: readUint(readTupleField(value, 'defenseCooldown', 10)),
  lootPercentageBps: readSafeUint(readTupleField(value, 'lootPercentageBps', 11), 65535),
  casualtyScaleBps: readSafeUint(readTupleField(value, 'casualtyScaleBps', 12), 65535),
  successfulRaidXP: readUint(readTupleField(value, 'successfulRaidXP', 13)),
  successfulDefenseXP: readUint(readTupleField(value, 'successfulDefenseXP', 14)),
  troopAttackStrength: readUint(readTupleField(value, 'troopAttackStrength', 15)),
  troopDefenseStrength: readUint(readTupleField(value, 'troopDefenseStrength', 16)),
  troopCarryPoints: readUint(readTupleField(value, 'troopCarryPoints', 17)),
  troopCarryLifetime: readUint(readTupleField(value, 'troopCarryLifetime', 18)),
  maxTroopsPerLand: readUint(readTupleField(value, 'maxTroopsPerLand', 19)),
});

export const normalizeBarracksTroopConfigV2 = (value: unknown) => ({
  trainingToken: readAddress(readTupleField(value, 'trainingToken', 0)),
  trainingCost: readUint(readTupleField(value, 'trainingCost', 1)),
  trainingReceiver: readAddress(readTupleField(value, 'trainingReceiver', 2)),
  trainingTimePerTroop: readUint(readTupleField(value, 'trainingTimePerTroop', 3)),
  troopAttackStrength: readUint(readTupleField(value, 'troopAttackStrength', 4)),
  troopDefenseStrength: readUint(readTupleField(value, 'troopDefenseStrength', 5)),
  troopCarryPoints: readUint(readTupleField(value, 'troopCarryPoints', 6)),
  troopCarryLifetime: readUint(readTupleField(value, 'troopCarryLifetime', 7)),
  maxTroopsPerLand: readUint(readTupleField(value, 'maxTroopsPerLand', 8)),
});

export const normalizeBarracksConfigV2 = (value: unknown): BarracksConfigV2 => ({
  initialized: readBoolean(readTupleField(value, 'initialized', 0)),
  enabled: readBoolean(readTupleField(value, 'enabled', 1)),
  buildToken: readAddress(readTupleField(value, 'buildToken', 2)),
  buildCost: readUint(readTupleField(value, 'buildCost', 3)),
  buildReceiver: readAddress(readTupleField(value, 'buildReceiver', 4)),
  attackCooldown: readUint(readTupleField(value, 'attackCooldown', 5)),
  defenseCooldown: readUint(readTupleField(value, 'defenseCooldown', 6)),
  lootPercentageBps: readSafeUint(readTupleField(value, 'lootPercentageBps', 7), 65535),
  casualtyScaleBps: readSafeUint(readTupleField(value, 'casualtyScaleBps', 8), 65535),
  successfulRaidXP: readUint(readTupleField(value, 'successfulRaidXP', 9)),
  successfulDefenseXP: readUint(readTupleField(value, 'successfulDefenseXP', 10)),
  swordsman: normalizeBarracksTroopConfigV2(readTupleField(value, 'swordsman', 11)),
  phalanx: normalizeBarracksTroopConfigV2(readTupleField(value, 'phalanx', 12)),
});

export const normalizeBarracksLandState = (value: unknown): BarracksLandState => ({
  isBuilt: readBoolean(readTupleField(value, 'isBuilt', 0)),
  stationedTroops: readUint(readTupleField(value, 'stationedTroops', 1)),
  trainingQueueAmount: readUint(readTupleField(value, 'trainingQueueAmount', 2)),
  readyToClaimTroops: readUint(readTupleField(value, 'readyToClaimTroops', 3)),
  trainingStartedAt: readUint(readTupleField(value, 'trainingStartedAt', 4)),
  trainingEndsAt: readUint(readTupleField(value, 'trainingEndsAt', 5)),
  nextTroopReadyAt: readUint(readTupleField(value, 'nextTroopReadyAt', 6)),
  lastAttackAt: readUint(readTupleField(value, 'lastAttackAt', 7)),
  lastDefendedAt: readUint(readTupleField(value, 'lastDefendedAt', 8)),
  attackCooldownEndsAt: readUint(readTupleField(value, 'attackCooldownEndsAt', 9)),
  defenseCooldownEndsAt: readUint(readTupleField(value, 'defenseCooldownEndsAt', 10)),
  totalTroops: readUint(readTupleField(value, 'totalTroops', 11)),
});

export const normalizeBarracksLandStateV2 = (value: unknown): BarracksLandStateV2 => ({
  isBuilt: readBoolean(readTupleField(value, 'isBuilt', 0)),
  stationedSwordsmanTroops: readUint(readTupleField(value, 'stationedSwordsmanTroops', 1)),
  stationedPhalanxTroops: readUint(readTupleField(value, 'stationedPhalanxTroops', 2)),
  trainingQueueTroopType: readSafeUint(readTupleField(value, 'trainingQueueTroopType', 3), 255),
  trainingQueueAmount: readUint(readTupleField(value, 'trainingQueueAmount', 4)),
  readyToClaimSwordsmanTroops: readUint(readTupleField(value, 'readyToClaimSwordsmanTroops', 5)),
  readyToClaimPhalanxTroops: readUint(readTupleField(value, 'readyToClaimPhalanxTroops', 6)),
  trainingStartedAt: readUint(readTupleField(value, 'trainingStartedAt', 7)),
  trainingEndsAt: readUint(readTupleField(value, 'trainingEndsAt', 8)),
  nextTroopReadyAt: readUint(readTupleField(value, 'nextTroopReadyAt', 9)),
  lastAttackAt: readUint(readTupleField(value, 'lastAttackAt', 10)),
  lastDefendedAt: readUint(readTupleField(value, 'lastDefendedAt', 11)),
  attackCooldownEndsAt: readUint(readTupleField(value, 'attackCooldownEndsAt', 12)),
  defenseCooldownEndsAt: readUint(readTupleField(value, 'defenseCooldownEndsAt', 13)),
  totalSwordsmanTroops: readUint(readTupleField(value, 'totalSwordsmanTroops', 14)),
  totalPhalanxTroops: readUint(readTupleField(value, 'totalPhalanxTroops', 15)),
});

export const normalizeBarracksRaidReport = (value: unknown): BarracksRaidReport => ({
  raidId: readUint(readTupleField(value, 'raidId', 0)),
  timestamp: readUint(readTupleField(value, 'timestamp', 1)),
  attackerLandId: readUint(readTupleField(value, 'attackerLandId', 2)),
  defenderLandId: readUint(readTupleField(value, 'defenderLandId', 3)),
  attackerWon: readBoolean(readTupleField(value, 'attackerWon', 4)),
  troopsSent: readUint(readTupleField(value, 'troopsSent', 5)),
  attackerTroopsBefore: readUint(readTupleField(value, 'attackerTroopsBefore', 6)),
  defenderTroopsBefore: readUint(readTupleField(value, 'defenderTroopsBefore', 7)),
  attackerTroopsLost: readUint(readTupleField(value, 'attackerTroopsLost', 8)),
  defenderTroopsLost: readUint(readTupleField(value, 'defenderTroopsLost', 9)),
  survivingAttackers: readUint(readTupleField(value, 'survivingAttackers', 10)),
  survivingDefenders: readUint(readTupleField(value, 'survivingDefenders', 11)),
  attackerPower: readUint(readTupleField(value, 'attackerPower', 12)),
  defenderPower: readUint(readTupleField(value, 'defenderPower', 13)),
  pendingPointsSettled: readUint(readTupleField(value, 'pendingPointsSettled', 14)),
  pendingLifetimeSettled: readUint(readTupleField(value, 'pendingLifetimeSettled', 15)),
  pointsStolen: readUint(readTupleField(value, 'pointsStolen', 16)),
  lifetimeStolen: readUint(readTupleField(value, 'lifetimeStolen', 17)),
});

export const normalizeBarracksRaidReportV2 = (value: unknown): BarracksRaidReportV2 => ({
  raidId: readUint(readTupleField(value, 'raidId', 0)),
  timestamp: readUint(readTupleField(value, 'timestamp', 1)),
  attackerLandId: readUint(readTupleField(value, 'attackerLandId', 2)),
  defenderLandId: readUint(readTupleField(value, 'defenderLandId', 3)),
  attackerWon: readBoolean(readTupleField(value, 'attackerWon', 4)),
  swordsmenSent: readUint(readTupleField(value, 'swordsmenSent', 5)),
  phalanxSent: readUint(readTupleField(value, 'phalanxSent', 6)),
  attackerSwordsmenBefore: readUint(readTupleField(value, 'attackerSwordsmenBefore', 7)),
  attackerPhalanxBefore: readUint(readTupleField(value, 'attackerPhalanxBefore', 8)),
  defenderSwordsmenBefore: readUint(readTupleField(value, 'defenderSwordsmenBefore', 9)),
  defenderPhalanxBefore: readUint(readTupleField(value, 'defenderPhalanxBefore', 10)),
  attackerSwordsmenLost: readUint(readTupleField(value, 'attackerSwordsmenLost', 11)),
  attackerPhalanxLost: readUint(readTupleField(value, 'attackerPhalanxLost', 12)),
  defenderSwordsmenLost: readUint(readTupleField(value, 'defenderSwordsmenLost', 13)),
  defenderPhalanxLost: readUint(readTupleField(value, 'defenderPhalanxLost', 14)),
  survivingAttackerSwordsmen: readUint(readTupleField(value, 'survivingAttackerSwordsmen', 15)),
  survivingAttackerPhalanx: readUint(readTupleField(value, 'survivingAttackerPhalanx', 16)),
  survivingDefenderSwordsmen: readUint(readTupleField(value, 'survivingDefenderSwordsmen', 17)),
  survivingDefenderPhalanx: readUint(readTupleField(value, 'survivingDefenderPhalanx', 18)),
  attackerPower: readUint(readTupleField(value, 'attackerPower', 19)),
  defenderPower: readUint(readTupleField(value, 'defenderPower', 20)),
  pendingPointsSettled: readUint(readTupleField(value, 'pendingPointsSettled', 21)),
  pendingLifetimeSettled: readUint(readTupleField(value, 'pendingLifetimeSettled', 22)),
  pointsStolen: readUint(readTupleField(value, 'pointsStolen', 23)),
  lifetimeStolen: readUint(readTupleField(value, 'lifetimeStolen', 24)),
});

export const normalizeBarracksRaidPreview = (value: unknown): BarracksRaidPreview => ({
  statusCode: readSafeUint(readTupleField(value, 'statusCode', 0), 255),
  attackerWon: readBoolean(readTupleField(value, 'attackerWon', 1)),
  troopsRequested: readUint(readTupleField(value, 'troopsRequested', 2)),
  attackerTroopsBefore: readUint(readTupleField(value, 'attackerTroopsBefore', 3)),
  defenderTroopsBefore: readUint(readTupleField(value, 'defenderTroopsBefore', 4)),
  attackerTroopsLost: readUint(readTupleField(value, 'attackerTroopsLost', 5)),
  defenderTroopsLost: readUint(readTupleField(value, 'defenderTroopsLost', 6)),
  survivingAttackers: readUint(readTupleField(value, 'survivingAttackers', 7)),
  survivingDefenders: readUint(readTupleField(value, 'survivingDefenders', 8)),
  attackerPower: readUint(readTupleField(value, 'attackerPower', 9)),
  defenderPower: readUint(readTupleField(value, 'defenderPower', 10)),
  pendingPoints: readUint(readTupleField(value, 'pendingPoints', 11)),
  pendingLifetime: readUint(readTupleField(value, 'pendingLifetime', 12)),
  carryPointsCap: readUint(readTupleField(value, 'carryPointsCap', 13)),
  carryLifetimeCap: readUint(readTupleField(value, 'carryLifetimeCap', 14)),
  estimatedPointsLoot: readUint(readTupleField(value, 'estimatedPointsLoot', 15)),
  estimatedLifetimeLoot: readUint(readTupleField(value, 'estimatedLifetimeLoot', 16)),
  attackerCooldownEndsAt: readUint(readTupleField(value, 'attackerCooldownEndsAt', 17)),
  defenderCooldownEndsAt: readUint(readTupleField(value, 'defenderCooldownEndsAt', 18)),
});

export const normalizeBarracksRaidPreviewV2 = (value: unknown): BarracksRaidPreviewV2 => ({
  statusCode: readSafeUint(readTupleField(value, 'statusCode', 0), 255),
  attackerWon: readBoolean(readTupleField(value, 'attackerWon', 1)),
  swordsmenRequested: readUint(readTupleField(value, 'swordsmenRequested', 2)),
  phalanxRequested: readUint(readTupleField(value, 'phalanxRequested', 3)),
  attackerSwordsmenBefore: readUint(readTupleField(value, 'attackerSwordsmenBefore', 4)),
  attackerPhalanxBefore: readUint(readTupleField(value, 'attackerPhalanxBefore', 5)),
  defenderSwordsmenBefore: readUint(readTupleField(value, 'defenderSwordsmenBefore', 6)),
  defenderPhalanxBefore: readUint(readTupleField(value, 'defenderPhalanxBefore', 7)),
  attackerSwordsmenLost: readUint(readTupleField(value, 'attackerSwordsmenLost', 8)),
  attackerPhalanxLost: readUint(readTupleField(value, 'attackerPhalanxLost', 9)),
  defenderSwordsmenLost: readUint(readTupleField(value, 'defenderSwordsmenLost', 10)),
  defenderPhalanxLost: readUint(readTupleField(value, 'defenderPhalanxLost', 11)),
  survivingAttackerSwordsmen: readUint(readTupleField(value, 'survivingAttackerSwordsmen', 12)),
  survivingAttackerPhalanx: readUint(readTupleField(value, 'survivingAttackerPhalanx', 13)),
  survivingDefenderSwordsmen: readUint(readTupleField(value, 'survivingDefenderSwordsmen', 14)),
  survivingDefenderPhalanx: readUint(readTupleField(value, 'survivingDefenderPhalanx', 15)),
  attackerPower: readUint(readTupleField(value, 'attackerPower', 16)),
  defenderPower: readUint(readTupleField(value, 'defenderPower', 17)),
  pendingPoints: readUint(readTupleField(value, 'pendingPoints', 18)),
  pendingLifetime: readUint(readTupleField(value, 'pendingLifetime', 19)),
  carryPointsCap: readUint(readTupleField(value, 'carryPointsCap', 20)),
  carryLifetimeCap: readUint(readTupleField(value, 'carryLifetimeCap', 21)),
  estimatedPointsLoot: readUint(readTupleField(value, 'estimatedPointsLoot', 22)),
  estimatedLifetimeLoot: readUint(readTupleField(value, 'estimatedLifetimeLoot', 23)),
  attackerCooldownEndsAt: readUint(readTupleField(value, 'attackerCooldownEndsAt', 24)),
  defenderCooldownEndsAt: readUint(readTupleField(value, 'defenderCooldownEndsAt', 25)),
});
