import { CLIENT_ENV } from './env-config';
import { PIXOTCHI_ADDRESS, SEED_ADDRESS } from './swap/constants';

export const PIXOTCHI_TOKEN_INFO_IDS = ['seed', 'leaf', 'pixotchi'] as const;

export type PixotchiTokenInfoId = typeof PIXOTCHI_TOKEN_INFO_IDS[number];

export type PixotchiTokenInfoBullet = {
  body: string;
  label?: string;
};

export type PixotchiTokenInfoSection = {
  body: string;
  bullets?: readonly PixotchiTokenInfoBullet[];
  iconAlt: string;
  iconSrc: string;
  key: string;
  title: string;
};

export type PixotchiTokenInfo = {
  contractAddress: string;
  iconAlt: string;
  iconSrc: string;
  id: PixotchiTokenInfoId;
  name: string;
  noFinancialAdvice: true;
  note?: string;
  sections: readonly PixotchiTokenInfoSection[];
  summary: string;
  symbol: string;
};

export const INITIAL_SEED_SUPPLY = BigInt(20_000_000) * BigInt(10) ** BigInt(18);
export const PERCENTAGE_BASIS_POINTS = BigInt(10_000);
export const PIXOTCHI_BATCH_CLAIM_BURN_AMOUNT = Number(process.env.NEXT_PUBLIC_BATCH_CLAIM_BURN_AMOUNT || 500);
export const PIXOTCHI_BATCH_CLAIM_MAX_SIZE = Number(process.env.NEXT_PUBLIC_BATCH_CLAIM_MAX_SIZE || 150);

const TOKEN_INFO = {
  seed: {
    contractAddress: SEED_ADDRESS,
    iconAlt: 'SEED token',
    iconSrc: '/PixotchiKit/COIN.svg',
    id: 'seed',
    name: 'Core economy token',
    noFinancialAdvice: true,
    note: 'SEED was launched independently via BaseSwap with 100% of the supply (20M) in circulation, with no pre-mint or team allocation. Acquiring SEED does not represent an investment contract or financial advice.',
    sections: [
      {
        body: 'Currently, 70% of SEED spent inside the game on items or upgrades is permanently burned. The remaining 30% is recycled into the rewards pool.',
        iconAlt: 'Burn',
        iconSrc: '/icons/fire.svg',
        key: 'seed-burn',
        title: '70% In-Game Burn',
      },
      {
        body: 'A 5% tax applies to SEED swaps to sustain the ecosystem and support rewards, development, and liquidity.',
        bullets: [
          { body: 'Distributed as ETH based on plant ranking.', label: '2% to Player Rewards' },
          { body: 'Funds ongoing development and operations.', label: '2% to Project Treasury' },
          { body: 'Added to the SEED/ETH pool for stability.', label: '1% to Liquidity Pool' },
        ],
        iconAlt: 'Tax',
        iconSrc: '/icons/tax.svg',
        key: 'seed-tax',
        title: '5% Buy/Sell Tax',
      },
      {
        body: '2% of SEED trading volume is distributed daily to plants as ETH based on their points. Higher points means a larger share of the daily reward pool.',
        iconAlt: 'Rewards',
        iconSrc: '/icons/ethlogo.svg',
        key: 'seed-rewards',
        title: 'Rewards Distributed Today',
      },
    ],
    summary: 'The fixed-supply currency that powers plant actions, upgrades, swaps, staking access, and the wider Pixotchi economy.',
    symbol: 'SEED',
  },
  leaf: {
    contractAddress: CLIENT_ENV.LEAF_CONTRACT_ADDRESS,
    iconAlt: 'LEAF token',
    iconSrc: '/icons/leaf.png',
    id: 'leaf',
    name: 'Land progression resource',
    noFinancialAdvice: true,
    sections: [
      {
        body: 'LEAF is generated by staking SEED. Rewards accrue over time and can be claimed, giving players who stake a free way to earn PTS/TOD and access more features instead of burning their SEED tokens, without turning LEAF into a public-market token.',
        bullets: [
          { body: 'Stake SEED to generate LEAF continuously.' },
          { body: 'Seasonal reward programs and airdrops may also distribute LEAF when active.' },
        ],
        iconAlt: 'Staking',
        iconSrc: '/icons/stake-house.svg',
        key: 'leaf-staking',
        title: 'Earned Through Staking',
      },
      {
        body: 'LEAF is mainly used for Land development: upgrading buildings, unlocking higher production tiers, and supporting long-term village efficiency. New features and utility are planned.',
        iconAlt: 'Lands',
        iconSrc: '/icons/village-start.png',
        key: 'leaf-lands',
        title: 'Built For Lands',
      },
      {
        body: 'LEAF has no external liquidity pool. It is tradable only inside the Marketplace building through player-created SEED/LEAF orders, keeping price discovery inside the game economy.',
        iconAlt: 'Marketplace',
        iconSrc: '/icons/marketplace.svg',
        key: 'leaf-marketplace',
        title: 'In-Game Marketplace Only',
      },
    ],
    summary: 'An internal progression token earned from staking SEED and used mainly to develop Lands and long-term village systems.',
    symbol: 'LEAF',
  },
  pixotchi: {
    contractAddress: PIXOTCHI_ADDRESS,
    iconAlt: 'PIXOTCHI Creator Coin',
    iconSrc: '/icons/cc.png',
    id: 'pixotchi',
    name: 'Creator Coin layer',
    noFinancialAdvice: true,
    sections: [
      {
        body: 'A Zora Creator Coin adapted for gameplay, adding useful actions beyond open-market trading.',
        iconAlt: 'Zora',
        iconSrc: '/icons/zora.png',
        key: 'pixotchi-creator-coin',
        title: 'Creator Coin, Game-First',
      },
      {
        body: `Covers instant building upgrades, Casino plays, and batch claims of up to ${PIXOTCHI_BATCH_CLAIM_MAX_SIZE} buildings for ${PIXOTCHI_BATCH_CLAIM_BURN_AMOUNT} tokens.`,
        iconAlt: 'Wallet profile',
        iconSrc: '/icons/Avatar2.svg',
        key: 'pixotchi-utility',
        title: 'In-Game Utility Layer',
      },
      {
        body: 'Fixed 1B supply: 50% entered the market and 50% vests to the creator over five years. Zora fees deepen permanent liquidity.',
        iconAlt: 'PIXOTCHI token',
        iconSrc: '/icons/cc.png',
        key: 'pixotchi-tokenomics',
        title: 'Tokenomics',
      },
    ],
    summary: 'A Zora Creator Coin connected to real gameplay utility, not passive ownership.',
    symbol: 'PIXOTCHI',
  },
} as const satisfies Record<PixotchiTokenInfoId, PixotchiTokenInfo>;

export function getPixotchiTokenInfo(token: PixotchiTokenInfoId): PixotchiTokenInfo {
  return TOKEN_INFO[token];
}

export function getAllPixotchiTokenInfo(): PixotchiTokenInfo[] {
  return PIXOTCHI_TOKEN_INFO_IDS.map((token) => TOKEN_INFO[token]);
}
