export const VERIFY_CLAIM_LEAF_BONUS_AMOUNT = "7000000";
export const VERIFY_CLAIM_SEED_BONUS_AMOUNT = "100";

export const VERIFY_CLAIM_LEAF_BONUS_LABEL = "7,000,000 LEAF";
export const VERIFY_CLAIM_SEED_BONUS_LABEL = "100 SEED";
