import assert from 'node:assert/strict';
import { getAirdropRecovery, publicAirdropStatus } from '../lib/airdrop-execution';
import { isAirdropTransactionHash, isAirdropUserOperationHash } from '../lib/airdrop-claim-reconciliation';
const hash = `0x${'a'.repeat(64)}` as const;
assert.equal(isAirdropUserOperationHash(hash), true);
assert.equal(isAirdropTransactionHash('0x1234'), false);
assert.equal(getAirdropRecovery({ status: 'failed', operationId: hash }).recoveryState, 'manual_review');
const claimed = publicAirdropStatus({ seed: '1.25', status: 'claimed', claimed: true, txHash: hash });
assert.equal(claimed.seed, '1.25');
assert.equal(claimed.retryAllowed, false);
assert.equal(claimed.txHash, hash);
console.log('Airdrop reconciliation/public projection smoke passed; full operation proof checks run in airdrop-execution-smoke.ts');
