import assert from 'node:assert/strict';
import { buildMarketplacePriceLevels, compareMarketplacePrices, computeMarketplaceAmountAsk, getMarketplaceRatioKey } from '../lib/marketplace-price';
import { getRouletteCombinationOptions } from '../lib/roulette-bet-options';
import { parseMarketplaceOrder } from '../lib/marketplace-order';
import { formatTokenCost, formatTokenDisplay, formatTokenDisplayCompact, formatTokenEstimate, formatTokenDecimal, formatTokenSymbol } from '../lib/token-display';
import { getBuildingPurchaseReadiness } from '../lib/building-purchase-readiness';
import { formatDurationSeconds } from '../lib/duration-display';
import { getUnlockedQuestSlots, parseQuestSlots, summarizeQuestSlots } from '../lib/quest-slots';
import { parseAmountInput } from '../lib/amount-input';
import { parseCasinoAmountInput } from '../lib/casino-amount-input';
import { extractTransactionHash, normalizeTransactionReceipt, getHighestTransactionReceiptBlock, parseReceiptBlock } from '../lib/transaction-utils';
import { getAtomicCapabilityStatus, getErrorStatusName, getNestedErrorCode, isUnresolvedWaitError, isDefinitivePostSubmissionError } from '../lib/transaction-lifecycle';
import { formatEditableAmount, parseInputAmount } from '../lib/swap/amount';
import { parseFirstCareProgress } from '../lib/first-care-progress';
import { calculateHandValue } from '../lib/blackjack-cards';
import { deriveInitialPlayerActions, hasTrustedActionState, parseBlackjackSnapshot, reconcileTurnCards } from '../lib/blackjack-state';
import { BlackjackPhase } from '../public/abi/blackjack-abi';
import { canPlantAttack, getPlantAttackAvailability, getPlantAttackReadyAt, type AttackPlant } from '../lib/plant-attack';

const attackNow = 1_800_000_000;
const readyAttacker: AttackPlant = { id: 1, owner: '0xA', status: 0, level: 2, lastAttackUsed: '0', lastAttacked: '0' };
const restingAttacker = { ...readyAttacker, lastAttackUsed: String(attackNow - 600) };
const attackTarget = { ...readyAttacker, id: 2, owner: '0xB', level: 3 };
assert.deepEqual(getPlantAttackAvailability([restingAttacker], attackNow), { kind: 'cooldown', readyAt: attackNow + 1200, livingCount: 1 });
assert.deepEqual(getPlantAttackAvailability([restingAttacker, { ...restingAttacker, id: 3, lastAttackUsed: String(attackNow - 1200) }], attackNow), { kind: 'cooldown', readyAt: attackNow + 600, livingCount: 2 });
assert.equal(getPlantAttackAvailability([restingAttacker, readyAttacker], attackNow).kind, 'ready', 'One resting plant cannot block a ready one');
assert.equal(getPlantAttackAvailability([{ ...restingAttacker, status: 4 }], attackNow).kind, 'no-living-plants');
assert.equal(getPlantAttackAvailability([], attackNow).kind, 'no-plants');
assert.equal(getPlantAttackAvailability([restingAttacker], attackNow + 1200).kind, 'ready');
for (const timestamp of ['', '-1', 'NaN', 'Infinity', '1.5', '9007199254740991']) {
  assert.equal(getPlantAttackReadyAt(timestamp), null);
  assert.equal(getPlantAttackAvailability([{ ...readyAttacker, lastAttackUsed: timestamp }], attackNow).kind, 'unavailable');
}
assert.equal(canPlantAttack(readyAttacker, attackTarget, attackNow, false), true);
assert.equal(canPlantAttack(restingAttacker, attackTarget, attackNow, false), false);
assert.equal(canPlantAttack(restingAttacker, attackTarget, attackNow + 1200, false), true);
assert.equal(canPlantAttack(readyAttacker, attackTarget, attackNow, true), false);
for (const target of [
  { ...attackTarget, status: 4 }, { ...attackTarget, level: 2 }, { ...attackTarget, level: 1 },
  { ...attackTarget, owner: '0xa' }, { ...attackTarget, lastAttacked: String(attackNow - 3599) },
  { ...attackTarget, lastAttacked: 'invalid' },
]) assert.equal(canPlantAttack(readyAttacker, target, attackNow, false), false);
assert.equal(canPlantAttack(readyAttacker, { ...attackTarget, lastAttacked: String(attackNow - 3600) }, attackNow, false), true);

const B = BigInt;
const sellLeaf = [100, 1000].map(n => ({ sellToken: 1, amount: B(n), amountAsk: B(1) }));
const sellSeed = [100, 1000].map(n => ({ sellToken: 0, amount: B(1), amountAsk: B(n) }));
assert.equal(computeMarketplaceAmountAsk('SEED', B(1), buildMarketplacePriceLevels(sellLeaf, 1)[0]!.exactRatio), B(1000), 'Selling SEED selects the most LEAF received');
assert.equal(computeMarketplaceAmountAsk('LEAF', B(1000), buildMarketplacePriceLevels(sellSeed, 0)[0]!.exactRatio), B(10), 'Selling LEAF selects the most SEED received');
const tiny = [{ sellToken: 1, amount: B(1), amountAsk: B(10) ** B(24) }, { sellToken: 1, amount: B(2), amountAsk: B(10) ** B(24) }];
assert.equal(buildMarketplacePriceLevels(tiny, 1).length, 2, 'Sub-display-precision rates must not merge');
const huge = B(10) ** B(40);
assert.equal(compareMarketplacePrices({ leafAmount: huge, seedAmount: B(1) }, { leafAmount: huge + B(1), seedAmount: B(1) }), -1);
assert.equal(getMarketplaceRatioKey({ leafAmount: B(2), seedAmount: B(6) }), getMarketplaceRatioKey({ leafAmount: B(1), seedAmount: B(3) }));
assert.equal(buildMarketplacePriceLevels([{ sellToken: 1, amount: B(0), amountAsk: B(1) }], 1).length, 0);

const counts = { split: 57, street: 12, corner: 22, 'six-line': 11 } as const;
for (const kind of Object.keys(counts) as Array<keyof typeof counts>) {
  const options = getRouletteCombinationOptions(kind);
  assert.equal(options.length, counts[kind], `${kind} covers the complete supported table`);
  assert.equal(new Set(options.map(o => o.numbers.join(','))).size, options.length);
  for (const option of options) {
    assert.ok(option.numbers.every(n => n >= 1 && n <= 36));
    assert.equal(new Set(option.numbers).size, option.numbers.length);
  }
}
assert.ok(getRouletteCombinationOptions('split').some(o => o.numbers.join(',') === '3,6'));
const validOrder = { id: B(1), seller: '0x0000000000000000000000000000000000000001', sellToken: 1, amount: B(5), amountAsk: B(1), isActive: true };
assert.equal(parseMarketplaceOrder(validOrder).amount, B(5));
assert.throws(() => parseMarketplaceOrder({ ...validOrder, amount: B(0) }));
assert.throws(() => parseMarketplaceOrder({ ...validOrder, amountAsk: B(0) }));
assert.equal(parseMarketplaceOrder({ ...validOrder, amount: B(0), isActive: false }).isActive, false);
for (const malformed of [null, {}, { ...validOrder, sellToken: 2 }, { ...validOrder, amount: 5 }, { ...validOrder, amount: B(-1) }, { ...validOrder, seller: 'invalid' }, { ...validOrder, isActive: 'true' }]) {
  assert.throws(() => parseMarketplaceOrder(malformed));
}
assert.equal(formatTokenDisplay(B('6189625000000000000')), '6.18');
const barracksCost = B('250000000000000000000');
const barracksBalance = B('6189625053348471150');
assert.equal(formatTokenDisplay(barracksBalance), '6.18', 'Balances never display spendable funds the wallet does not have');
assert.equal(formatTokenCost(barracksCost - barracksBalance), '243.82', 'Readable shortfalls round up so the suggested amount covers the deficit');
assert.equal(formatTokenCost(B('499999999999999991611392')), '500,000', 'Near-integer contract costs do not leak decimal tails into the UI');
assert.equal(formatTokenCost(B('25879000'), 6), '25.88');
assert.equal(formatTokenCost(B('25000000'), 6), '25');
assert.equal(formatTokenCost(B(1), 18), '<0.01', 'Tiny costs remain visibly nonzero');
assert.equal(formatTokenCost(B(0)), '0');
assert.equal(formatTokenCost(B(250), 0), '250');
assert.equal(formatTokenCost(B('9007199254740993123456789123456789')), '9,007,199,254,740,993.13', 'Large costs never pass through Number');
assert.equal(getBuildingPurchaseReadiness({ cost: barracksCost, balance: barracksCost - B(1), allowance: barracksCost }), 'insufficient', 'Presentation precision must not relax exact affordability checks');
assert.equal(formatTokenSymbol('pixotchi'), 'PIXOTCHI');
assert.equal(formatTokenSymbol('seed'), 'SEED');
assert.equal(formatTokenSymbol('MixedCaseToken'), 'MixedCaseToken', 'Unknown token branding is preserved');
assert.equal(formatTokenDisplay(B(1)), '<0.01');
assert.equal(formatTokenDisplay(B(0)), '0');
assert.equal(formatTokenDisplay(B('9007199254740993000000000000000000')), '9,007,199,254,740,993');
assert.equal(formatTokenDisplayCompact(B('2999999999999999999999')), '2.99K');
assert.equal(formatTokenEstimate(B(1)), '~<0.000001');
assert.equal(formatTokenDecimal('0.000000000000000001', 18, 'exact'), '0.000000000000000001');
assert.equal(formatTokenDecimal('9007199254740993.123456789123456789', 18, 'exact'), '9,007,199,254,740,993.123456789123456789');
assert.equal(formatTokenDecimal('2999.999', 18, 'compact'), '2.99K');
for (const value of ['NaN', 'Infinity', '1e3', '-1', '0.0000001']) assert.equal(formatTokenDecimal(value, 6), null);
assert.equal(formatDurationSeconds(B(400 * 86400 + 3661)), '400d 1h', 'Durations retain total days across calendar months and years');
assert.equal(formatDurationSeconds(B(400 * 86400 + 3661), 'exact'), '400d 1h 1m 1s');
assert.equal(formatDurationSeconds(B(1)), '1s');
assert.equal(formatDurationSeconds(B(-1)), '0s');
const idleQuest = { difficulty: 0, startBlock: B(0), endBlock: B(0), pseudoRndBlock: B(0), coolDownBlock: B(0) };
assert.deepEqual(parseQuestSlots([[0, '0x0', B(0), 0, '0']]), [idleQuest]);
for (const value of [null, {}, [null], [{}], [[0, B(0)]], [{ ...idleQuest, difficulty: 3 }], [{ ...idleQuest, endBlock: true }], [{ ...idleQuest, startBlock: Number.MAX_SAFE_INTEGER + 1 }]]) assert.throws(() => parseQuestSlots(value));
const allQuestStates = [idleQuest, { ...idleQuest, startBlock: B(110), endBlock: B(356) }, { ...idleQuest, startBlock: B(1), endBlock: B(355) }, { ...idleQuest, startBlock: B(1), pseudoRndBlock: B(100) }, { ...idleQuest, startBlock: B(1), pseudoRndBlock: B(99) }, { ...idleQuest, coolDownBlock: B(357) }];
assert.equal(getUnlockedQuestSlots(allQuestStates, 1).length, 1, 'The overview cannot count locked slots as available');
assert.equal(getUnlockedQuestSlots(allQuestStates, 4).length, 3);
assert.equal(getUnlockedQuestSlots(allQuestStates, NaN).length, 0);
assert.deepEqual(summarizeQuestSlots(allQuestStates, B(356)), { available: 1, in_progress: 1, ready_to_commit: 1, committed: 1, expired: 1, cooldown: 1 });
assert.equal(summarizeQuestSlots(allQuestStates, B(0)), null, 'An unknown current block cannot advertise available actions');
assert.equal(summarizeQuestSlots(allQuestStates, B(357))?.expired, 2, 'Loot expires on the block after its inclusive deadline');
assert.equal(parseAmountInput('0.000001', 6), B(1));
assert.equal(parseAmountInput('0.0000009', 6), null, 'excess precision must never be rounded into a transaction');
assert.equal(parseAmountInput('1e6'), null);
assert.equal(parseAmountInput('-1'), null);
assert.equal(parseAmountInput('.'), null);
assert.equal(parseCasinoAmountInput('1.2K', 6), B(1200000000));
assert.throws(() => parseCasinoAmountInput('1.0000001', 6));
const hash = `0x${'a'.repeat(64)}`;
for (const envelope of [{ transactionHash: hash }, { transaction: { hash } }, { receipts: [{ hash }] }, { transactions: [{ transactionHash: hash }] }, [{ hash }]]) assert.equal(extractTransactionHash(envelope), hash);
assert.equal(extractTransactionHash({ transactionHash: true, hash }), hash);
for (const invalid of [true, 123, '0x123', {}, { transactionHash: '0x123' }]) assert.equal(extractTransactionHash(invalid), undefined);
for (const invalid of [-1, 1.2, Number.MAX_SAFE_INTEGER + 1, true, '1.1', '-1', '']) assert.equal(parseReceiptBlock(invalid), undefined);
assert.equal(getHighestTransactionReceiptBlock([{ blockNumber: '0x10' }, { blockNumber: 20 }, { blockNumber: -9 }]), B(20));
const log = { address: `0x${'1'.repeat(40)}`, topics: [hash], data: '0x00' };
const receipt = normalizeTransactionReceipt({ transaction: { hash }, blockNumber: '0x10', status: 'success', logs: [log, { ...log, topics: ['0x1'] }], walletExtension: { id: 1 } });
assert.equal(receipt.transactionHash, hash);
assert.equal(receipt.blockNumber, B(16));
assert.equal(receipt.logs?.length, 1);
assert.deepEqual(receipt.walletExtension, { id: 1 });
assert.equal(normalizeTransactionReceipt({ transactionHash: 'invalid', blockNumber: true }).transactionHash, undefined);
assert.equal(getAtomicCapabilityStatus({ '0x2105': { atomic: { status: 'supported' } } }, 8453), 'supported');
assert.equal(getAtomicCapabilityStatus({ '8453': { atomic: { status: 'ready' } } }, 8453), 'ready');
assert.equal(getAtomicCapabilityStatus({ atomic: { status: true } }, 8453), null);
assert.equal(getErrorStatusName({ cause: { code: '4001' } }), 'transactionRejected');
assert.equal(getErrorStatusName(new Error('execution reverted')), 'reverted');
const cycle: { cause?: unknown } = {}; cycle.cause = cycle;
assert.equal(getNestedErrorCode(cycle), null);
assert.equal(isUnresolvedWaitError(new Error('network connection lost')), true);
assert.equal(isDefinitivePostSubmissionError(new Error('network connection lost')), false);
assert.equal(formatEditableAmount(B('123456789123456789'), 18), '0.123456789123456789');
assert.equal(parseInputAmount('0.0000000000000000009', 'ETH'), null);
assert.deepEqual(parseFirstCareProgress('{"care":"true","tasks":true}'), { care: false, tasks: true });
const blackjack = { isActive: true, player: '0x0000000000000000000000000000000000000001', phase: BlackjackPhase.PLAYER_TURN, betAmount: B(1), activeHandCount: 1, hasSplit: false, actionHandIndex: 0, hand1Cards: [9, 22], hand1Value: 20, hand2Cards: [], hand2Value: 0, dealerCards: [2], dealerValue: 3, canHit: true, canStand: true, canDouble: true, canSplit: true, canSurrender: true };
assert.deepEqual(parseBlackjackSnapshot(blackjack), blackjack);
assert.deepEqual(parseBlackjackSnapshot({ snapshot: Object.values(blackjack) }), blackjack);
for (const malformed of [null, {}, { ...blackjack, canHit: 'false' }, { ...blackjack, hand1Cards: [52] }, { ...blackjack, hand2Cards: ['0'] }, { ...blackjack, actionHandIndex: 2 }, { ...blackjack, phase: 4 }, { ...blackjack, player: 'bad' }, { ...blackjack, betAmount: true }]) assert.throws(() => parseBlackjackSnapshot(malformed));
assert.equal(hasTrustedActionState(blackjack), true);
assert.equal(hasTrustedActionState({ ...blackjack, isActive: false }), false);
assert.equal(hasTrustedActionState({ ...blackjack, hand1Cards: [2, 4] }), false, 'Conflicting split flags keep actions locked');
assert.equal(hasTrustedActionState({ ...blackjack, actionHandIndex: 1, hand2Cards: [2, 4] }), false, 'A second hand requires a confirmed split');
assert.equal(hasTrustedActionState({ ...blackjack, hasSplit: true, actionHandIndex: 1, hand2Cards: [2, 4], canSplit: false, canSurrender: false }), true, 'A second split hand retains Double with two cards');
assert.equal(calculateHandValue([0, 13, 9]), 12, 'Multiple aces soften without busting');
assert.equal(deriveInitialPlayerActions([9, 11]).canSplit, true, 'Different face cards share Blackjack value');
assert.deepEqual(reconcileTurnCards([9, 22, 2], [9, 22], BlackjackPhase.PLAYER_TURN), { cards: [9, 22, 2], usedFetched: false }, 'Lagging RPC cannot erase a receipt-derived card');
assert.equal(reconcileTurnCards([9, 22], [9, 22, 2], BlackjackPhase.PLAYER_TURN).usedFetched, true);
assert.equal(reconcileTurnCards([9, 22], [2, 3], BlackjackPhase.PLAYER_TURN).usedFetched, false);
assert.deepEqual(reconcileTurnCards([9, 22], [], BlackjackPhase.RESOLVED), { cards: [], usedFetched: true }, 'Finished games may reset the hand');
console.log('Frontend quality: exact prices, validated orders and amounts, consistent balances, and complete roulette combinations passed.');
